name: build
on: [push]
jobs:
  build-win32-dll:
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: choco install mingw -x86 --force
      - run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cd secrethub-xgo
          set GOARCH=386
          set CGO_ENABLED=1
          set CC=cl.exe
          go build -o ../Client.a -buildmode=c-archive secrethub_wrapper.go
      - run: dir
      - run: choco install swig
      - run: swig -csharp -namespace SecretHub secrethub.i
      - run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cl.exe /O2 /Fo secrethub_wrap.o secrethub_wrap.c
      - uses: actions/upload-artifact@v2 
        with: 
          name: secrethub_wrap.o
          path: ./secrethub_wrap.o
      - run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          link.exe /DLL /OUT:SecretHubXGO.dll secrethub_wrap.o Client.a
      - uses: actions/upload-artifact@v2 
        with: 
          name: SecretHubXGO.dll
          path: ./SecretHubXGO.dll
