name: build
on: [push]
defaults:
  run:
    shell: powershell
jobs:
  check-bats-version:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/upload-artifact@v2
      - run: tree "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
      - run: cl.exe /?
      - run: choco install swig
      - run: swig -csharp -namespace SecretHub secrethub.i
      - run: cd secrethub-xgo && GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -o ../Client.a -buildmode=c-archive secrethub_wrapper.go
      - run: cl.exe /arch x86 /O2 -o secrethub_wrap.o secrethub_wrap.c